# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Joey Leong
tagline:          'Aspiring Writer'
description:      'Welcome to my Personal Blog!'
url:              http://joeylzq.com

author:
  name:           'Joey Leong'
  url:

pages_list:
  About: '/about'
  Archive: '/archive'

paginate:         5
